/*
 * This file is generated by jOOQ.
 */
package notary.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import notary.db.tables.Tokens;
import notary.db.tables.Wallets;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Notary extends SchemaImpl {

    private static final long serialVersionUID = -1604372717;

    /**
     * The reference instance of <code>notary</code>
     */
    public static final Notary NOTARY = new Notary();

    /**
     * The table <code>notary.tokens</code>.
     */
    public final Tokens TOKENS = notary.db.tables.Tokens.TOKENS;

    /**
     * The table <code>notary.wallets</code>.
     */
    public final Wallets WALLETS = notary.db.tables.Wallets.WALLETS;

    /**
     * No further instances allowed
     */
    private Notary() {
        super("notary", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Tokens.TOKENS,
                Wallets.WALLETS);
    }
}
