/*
 * This file is generated by jOOQ.
 */
package notary.db;


import javax.annotation.Generated;

import notary.db.tables.Tokens;
import notary.db.tables.Wallets;


/**
 * Convenience access to all tables in notary
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>notary.tokens</code>.
     */
    public static final Tokens TOKENS = notary.db.tables.Tokens.TOKENS;

    /**
     * The table <code>notary.wallets</code>.
     */
    public static final Wallets WALLETS = notary.db.tables.Wallets.WALLETS;
}
