/*
 * This file is generated by jOOQ.
 */
package notary.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tokens implements Serializable {

    private static final long serialVersionUID = -184652638;

    private String wallet;
    private String token;

    public Tokens() {
    }

    public Tokens(Tokens value) {
        this.wallet = value.wallet;
        this.token = value.token;
    }

    public Tokens(
            String wallet,
            String token
    ) {
        this.wallet = wallet;
        this.token = token;
    }

    public String getWallet() {
        return this.wallet;
    }

    public void setWallet(String wallet) {
        this.wallet = wallet;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tokens (");

        sb.append(wallet);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
