/*
 * This file is generated by jOOQ.
 */
package notary.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Wallets implements Serializable {

    private static final long serialVersionUID = -1578804084;

    private String wallet;
    private String irohausername;

    public Wallets() {
    }

    public Wallets(Wallets value) {
        this.wallet = value.wallet;
        this.irohausername = value.irohausername;
    }

    public Wallets(
            String wallet,
            String irohausername
    ) {
        this.wallet = wallet;
        this.irohausername = irohausername;
    }

    public String getWallet() {
        return this.wallet;
    }

    public void setWallet(String wallet) {
        this.wallet = wallet;
    }

    public String getIrohausername() {
        return this.irohausername;
    }

    public void setIrohausername(String irohausername) {
        this.irohausername = irohausername;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Wallets (");

        sb.append(wallet);
        sb.append(", ").append(irohausername);

        sb.append(")");
        return sb.toString();
    }
}
