---
  - hosts: all
    gather_facts: no
    pre_tasks:

      - name: install python 2  # python installation (ansible hosts gather_facts requirement)
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
        changed_when: False

    roles:
      - { role: iroha }
      - { role: docker }
      - { role: notary }
