/*
 * This file is generated by jOOQ.
 */
package notary.db.tables.records;


import javax.annotation.Generated;

import notary.db.tables.Tokens;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TokensRecord extends TableRecordImpl<TokensRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -268900056;

    /**
     * Setter for <code>notary.tokens.wallet</code>.
     */
    public void setWallet(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>notary.tokens.wallet</code>.
     */
    public String getWallet() {
        return (String) get(0);
    }

    /**
     * Setter for <code>notary.tokens.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notary.tokens.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tokens.TOKENS.WALLET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tokens.TOKENS.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value1(String value) {
        setWallet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokensRecord
     */
    public TokensRecord() {
        super(Tokens.TOKENS);
    }

    /**
     * Create a detached, initialised TokensRecord
     */
    public TokensRecord(String wallet, String token) {
        super(Tokens.TOKENS);

        set(0, wallet);
        set(1, token);
    }
}
