/*
 * This file is generated by jOOQ.
 */
package notary.db.tables.records;


import javax.annotation.Generated;

import notary.db.tables.Wallets;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WalletsRecord extends TableRecordImpl<WalletsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 175795068;

    /**
     * Setter for <code>notary.wallets.wallet</code>.
     */
    public void setWallet(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>notary.wallets.wallet</code>.
     */
    public String getWallet() {
        return (String) get(0);
    }

    /**
     * Setter for <code>notary.wallets.irohausername</code>.
     */
    public void setIrohausername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notary.wallets.irohausername</code>.
     */
    public String getIrohausername() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Wallets.WALLETS.WALLET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Wallets.WALLETS.IROHAUSERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIrohausername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIrohausername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletsRecord value1(String value) {
        setWallet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletsRecord value2(String value) {
        setIrohausername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletsRecord
     */
    public WalletsRecord() {
        super(Wallets.WALLETS);
    }

    /**
     * Create a detached, initialised WalletsRecord
     */
    public WalletsRecord(String wallet, String irohausername) {
        super(Wallets.WALLETS);

        set(0, wallet);
        set(1, irohausername);
    }
}
