---

- name: Remove notary folder
  file:
    path: "/opt/notary"
    state: absent

- name: Create notary folder
  file:
    path: "/opt/notary"
    state: directory
    recurse: yes
    mode: 666

- name: Create iroha keys folder
  file:
    path: /opt/notary/iroha/keys
    state: directory
    recurse: yes


- name: Create ethereum directory
  file:
    path: "/opt/notary/ethereum/keys/{{ directory_map[lookup('env','PROFILE')] }}"
    state: directory
    recurse: yes

- name: Copy ethereum keys
  copy:
    src: "{{ playbook_dir }}/roles/ethereum/files/{{ item }}"
    dest: "/opt/notary/ethereum/keys/{{ directory_map[lookup('env','PROFILE')] }}"
  with_items:
    - vacuum.key
    - withdrawal.key
    - relay_registration.key


- name: Copy ethereum genesis as registration key
  copy:
    src: "{{ projectRoot }}/deploy/ethereum/keys/{{ directory_map[lookup('env','PROFILE')] }}/genesis.key"
    dest: "/opt/notary/ethereum/keys/{{ directory_map[lookup('env','PROFILE')] }}/registration.key"
  with_items:
  - registration.key
  - vacuum.key
  - withdrawal.key
  - relay_registration.key


- name: Copy ethereum notary key
  copy:
    src: "{{ projectRoot }}/deploy/ansible/roles/ethereum/files/notary_{{ inventory_hostname }}.key"
    dest: "/opt/notary/ethereum/keys/{{ directory_map[lookup('env','PROFILE')] }}/notary.key"


- name: Copy iroha node private key
  copy:
    src: "{{ projectRoot }}/deploy/ansible/roles/iroha/files/node_{{ inventory_hostname }}.priv"
    dest: /opt/notary/iroha/keys/node0.priv

- name: Copy iroha node public key
  copy:
    src: "{{ projectRoot }}/deploy/ansible/roles/iroha/files/node_{{ inventory_hostname }}.pub"
    dest: /opt/notary/iroha/keys/node0.pub

- name: cat
  shell: cat /opt/notary/iroha/keys/node0.pub
  register: key


- name: Copy iroha notary private key
  copy:
    src: "{{ projectRoot }}/deploy/ansible/roles/iroha/files/notary_{{ inventory_hostname }}.priv"
    dest: /opt/notary/iroha/keys/notary0@notary.priv


- name: Copy iroha notary public key
  copy:
    src: "{{ projectRoot }}/deploy/ansible/roles/iroha/files/notary_{{ inventory_hostname }}.pub"
    dest: /opt/notary/iroha/keys/notary0@notary.pub




- name: Copy other iroha private keys
  copy:
    src: "{{ projectRoot }}/deploy/iroha/keys/{{ item }}.priv"
    dest: "/opt/notary/iroha/keys/{{ item }}.priv"
  with_items:
    - btc_registration_service@notary
    - eth_registration_service@notary
    - eth_token_service@notary
    - mst_btc_registration_service@notary
    - vacuumer@notary
    - withdrawal@notary
  run_once: yes


- name: Copy other iroha public keys
  copy:
    src: "{{ projectRoot }}/deploy/iroha/keys/{{ item }}.pub"
    dest: "/opt/notary/iroha/keys/{{ item }}.pub"
  with_items:
    - btc_registration_service@notary
    - eth_registration_service@notary
    - eth_token_service@notary
    - mst_btc_registration_service@notary
    - vacuumer@notary
    - withdrawal@notary
  run_once: yes


- name: Copy other iroha files
  copy:
    src: "{{ item }}"
    dest: /opt/notary/iroha
  with_items:
    - "{{ projectRoot }}/deploy/iroha/entrypoint.sh"
    - "{{ projectRoot }}/deploy/iroha/config.docker"
    - "{{ projectRoot }}/deploy/ansible/roles/iroha/files/genesis.block"


- name: Make iroha entrypoint executable
  file:
    path: /opt/notary/iroha/entrypoint.sh
    mode: 0755


- name: Copy configs folder
  copy:
    src: "{{ projectRoot }}/configs"
    dest: /opt/


- name: Copy docker compose files
  copy:
    src: "{{ projectRoot }}/deploy/{{item}}"
    dest: "/opt/notary/{{item}}"
  with_items:
    - docker-compose-full.yml
    - docker-compose-base.yml
    - docker-compose-single.yml

- name: Get master eth address
  shell: "cat {{ playbook_dir }}/roles/ethereum/files/master_eth_address"
  register: master_eth_address
  delegate_to: localhost
  become: no

- name: Get relay registry eth address
  shell: "cat {{ playbook_dir }}/roles/ethereum/files/relay_registry_eth_address"
  register: relay_registry_eth_address
  delegate_to: localhost
  become: no

- name: Read eth pass
  shell: "cat {{ playbook_dir }}/roles/ethereum/files/eth_pass"
  register: eth_pass
  delegate_to: localhost
  become: no

- name: Shutdown compose
  docker_service:
    project_src: /opt/notary
    files:
      - docker-compose-full.yml
      - docker-compose-base.yml
      - docker-compose-single.yml
    state: absent

- name: Run compose base
  docker_service:
    project_src: /opt/notary
    pull: yes
    recreate: always
    files:
      - docker-compose-base.yml
      - docker-compose-full.yml
  environment:
    TAG: "{{ lookup('env','TAG') }}"
    PROFILE: "{{ lookup('env','PROFILE') }}"
    ETH_CREDENTIALS_PASSWORD: "{{ eth_pass.stdout }}"


- name: Run compose once
  docker_service:
    project_src: /opt/notary
    pull: yes
    recreate: always
    files:
      - docker-compose-single.yml
  environment:
    TAG: "{{ lookup('env','TAG') }}"
    PROFILE: "{{ lookup('env','PROFILE') }}"
    ETH_RELAY_REGISTRY: "{{ relay_registry_eth_address.stdout }}"
    ETH_MASTER_WALLET: "{{ master_eth_address.stdout }}"
    ETH_CREDENTIALS_PASSWORD: "{{ eth_pass.stdout }}"
  run_once: yes
