- name: Purge old Docker versions if any
  apt: purge=yes state=absent name={{ item }}
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Install packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-setuptools
    - python-pip

- name: Add GPG key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'


- name: Add repository
  shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

- name: Install docker
  apt:
    name: docker-ce={{ dockerVersion }}
    state: present
    update_cache: yes


- name: download docker-compose bin
  raw: curl -L https://github.com/docker/compose/releases/download/{{ dockerComposeVersion }}/docker-compose-`uname -s`-`uname -m` -o {{ execPath }}/docker-compose

- name: make docker-compose executable
  file:
    path: "{{ execPath }}/docker-compose"
    mode: "a+x"
