---

- name: remove existing python modules
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: install docker python modules
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-compose==1.22.0


- include_tasks: install_docker.yml
  when: ansible_distribution == 'Ubuntu'

#- include_tasks: clean_docker.yml

- include_tasks: login_docker.yml

