/*
 * This file is generated by jOOQ.
 */
package notary.db.tables;


import javax.annotation.Generated;

import notary.db.Notary;
import notary.db.tables.records.WalletsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Wallets extends TableImpl<WalletsRecord> {

    private static final long serialVersionUID = 2050077155;

    /**
     * The reference instance of <code>notary.wallets</code>
     */
    public static final Wallets WALLETS = new Wallets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WalletsRecord> getRecordType() {
        return WalletsRecord.class;
    }

    /**
     * The column <code>notary.wallets.wallet</code>.
     */
    public final TableField<WalletsRecord, String> WALLET = createField("wallet", org.jooq.impl.SQLDataType.VARCHAR(42).nullable(false), this, "");

    /**
     * The column <code>notary.wallets.irohausername</code>.
     */
    public final TableField<WalletsRecord, String> IROHAUSERNAME = createField("irohausername", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>notary.wallets</code> table reference
     */
    public Wallets() {
        this(DSL.name("wallets"), null);
    }

    /**
     * Create an aliased <code>notary.wallets</code> table reference
     */
    public Wallets(String alias) {
        this(DSL.name(alias), WALLETS);
    }

    /**
     * Create an aliased <code>notary.wallets</code> table reference
     */
    public Wallets(Name alias) {
        this(alias, WALLETS);
    }

    private Wallets(Name alias, Table<WalletsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Wallets(Name alias, Table<WalletsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Notary.NOTARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wallets as(String alias) {
        return new Wallets(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wallets as(Name alias) {
        return new Wallets(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Wallets rename(String name) {
        return new Wallets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Wallets rename(Name name) {
        return new Wallets(name, null);
    }
}
